
import tkinter as tk
from ..Utils import WIDTH, HEIGHT, DISPLAY_SIZE_MULTIPLIER

# Constants
HOME_BASE_POS = (WIDTH // 2, HEIGHT // 2)
ANIMAL_SPEED = 2 * DISPLAY_SIZE_MULTIPLIER
SPAWN_INTERVAL = 2000  
ANIMALS_CIRCLE_RADIUS = int(25 * DISPLAY_SIZE_MULTIPLIER)  # Radius of the animal circle
HOME_BASE_BOUNDARY_RADIUS = int(100 * DISPLAY_SIZE_MULTIPLIER)  # Radius of the home base boundary
INITIAL_PLAYER_HEALTH = 1000

FONT_SIZE = int(36 * DISPLAY_SIZE_MULTIPLIER)
WEAPON_IMAGE_SIZE = (int(100 * DISPLAY_SIZE_MULTIPLIER), int(100 * DISPLAY_SIZE_MULTIPLIER))
ANIMAL_IMAGE_SIZE = (int(75 * DISPLAY_SIZE_MULTIPLIER), int(75 * DISPLAY_SIZE_MULTIPLIER))
HOUSE_IMAGE_SIZE = (int(80 * DISPLAY_SIZE_MULTIPLIER), int(80 * DISPLAY_SIZE_MULTIPLIER))

# Center the home base on the screen
HOME_BASE_POS = (
    (WIDTH - HOUSE_IMAGE_SIZE[0]) // 2,
    (HEIGHT - HOUSE_IMAGE_SIZE[1]) // 2
)

RED_CIRCLE_RADIUS = 20 * DISPLAY_SIZE_MULTIPLIER 
RED_CIRCLE_DURATION = 300 * DISPLAY_SIZE_MULTIPLIER

NUMBER_OF_ANIMALS_IN_TRIAL = 100

BOMBARDINO_CROCODILO_RANGE = 450 * DISPLAY_SIZE_MULTIPLIER
BOMBINI_GUSINI_RANGE = 250 * DISPLAY_SIZE_MULTIPLIER