
import tkinter as tk
from ..Utils import WIDTH, HEIGHT, DISPLAY_SIZE_MULTIPLIER

# Constants
HOME_BASE_POS = (WIDTH // 2, HEIGHT // 2)
ANIMAL_SPEED = 2 * DISPLAY_SIZE_MULTIPLIER
SPAWN_INTERVAL = 2000  
ANIMALS_CIRCLE_RADIUS = 20 * DISPLAY_SIZE_MULTIPLIER  # Radius of the animal circle
HOME_BASE_BOUNDARY_RADIUS = 100 * DISPLAY_SIZE_MULTIPLIER  # Radius of the home base boundary
INITIAL_PLAYER_HEALTH = 100

FONT_SIZE = 36 * DISPLAY_SIZE_MULTIPLIER
WEAPON_IMAGE_SIZE = (100 * DISPLAY_SIZE_MULTIPLIER, 100 * DISPLAY_SIZE_MULTIPLIER)
ANIMAL_IMAGE_SIZE = (75 * DISPLAY_SIZE_MULTIPLIER, 75 * DISPLAY_SIZE_MULTIPLIER)
HOUSE_IMAGE_SIZE = (80 * DISPLAY_SIZE_MULTIPLIER, 80 * DISPLAY_SIZE_MULTIPLIER)

# Center the home base on the screen
HOME_BASE_POS = (
    (WIDTH - HOUSE_IMAGE_SIZE[0]) // 2,
    (HEIGHT - HOUSE_IMAGE_SIZE[1]) // 2
)

RED_CIRCLE_RADIUS = 20 * DISPLAY_SIZE_MULTIPLIER 
RED_CIRCLE_DURATION = 300 * DISPLAY_SIZE_MULTIPLIER

NUMBER_OF_ANIMALS_IN_TRIAL = 100